POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Rock Rio",
    "details": "Travis Scott cantando FE!N",
    "maximumAttendees": 10
}

###

POST http://localhost:3333/events/389f9e44-6d88-455d-b50b-18a8a7854660/attendees
Content-Type: application/json

{
    "name": "Lucas de Lima",
    "email": "lucaslnascimento010@gmail.com.br"
}

###

GET http://localhost:3333/events/389f9e44-6d88-455d-b50b-18a8a7854660

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/389f9e44-6d88-455d-b50b-18a8a7854660/attendees?query=lucas