POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Rock Rio",
    "details": "Travis Scott cantando FE!N",
    "maximumAttendees": 10
}

###

POST http://localhost:3333/events/0fced75c-6fbe-4f93-9483-8235e116a343/attendees
Content-Type: application/json

{
    "name": "Lucas de Lima",
    "email": "lucaslnascimento010@gmail.com.br"
}

###

GET http://localhost:3333/events/0fced75c-6fbe-4f93-9483-8235e116a343

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/0fced75c-6fbe-4f93-9483-8235e116a343/attendees?query=lucas